resources:
  - name: propertyCanvas
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      pipelines: 'user_in'
  - name: propertyCanvas2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1_with_a_long_long_name_try_this
        type: Bash
        configuration:
          affinityGroup: trigger
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 10
      - name: trigger_2_and_with_a_long_long_name_try_this
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_1_with_a_long_long_name_try_this
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 20
      - name: trigger_3
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_2_and_with_a_long_long_name_try_this
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 30
      - name: trigger_4
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_3
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 40
      - name: trigger_5
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_4
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 50
      - name: trigger_6
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_5
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 60
      - name: trigger_7
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_6
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
            - sleep 70
  - name: trigger_test
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_2
        type: Bash
        configuration:
          affinityGroup: g1
          environmentVariables:
            step2env1: 1
            step2env2: 2
          outputResources:
            - name: propertyCanvas
        execution:
          onExecute:
            - echo runs > cache.file
            - add_cache_files cache.file runs.file
            - echo "state=pipeline2" > cache.txt
            - add_run_files cache.txt run_state_file
            - add_pipeline_files cache.txt pipe_state_file
            - write_output propertyCanvas "pipelines=$run_id"
            - save_tests cache.txt
