resources:
  - name: mvnBuild_info
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_sample_build_varsha
      buildNumber: 9
  - name: mvnBuild_infoScaned
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_scan_varsha
      buildNumber: 2
  - name: propertyCanvasAkh
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      pipelines: 'user_in'
pipelines:
  - name: varshabash
    steps:
      - name: testReport_u16
        type: Bash
        configuration:
          nodePool: TestPoolAkhil
          runtime:
            type: image
            image:
              # auto:
              #   language: java
              #   versions:
              #     - openjdk8
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16go
                tag: 0.9.1 #master #
        execution:
          onExecute:
            - printenv
            - cd $res_script_repo1_resourcePath
            - python -m py_compile calc.py
            - sleep 20
            - pip install pytest
            - cd $res_script_repo1_resourcePath
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_script_repo1_resourcePath/test-reports/results.xml

  - name: varshamvn
    steps:
      # - name: input_script_bash
        type: Bash
        configuration:
          nodePool: TestPoolAkhil
          runtime:
            type: image
            image:
              # auto:
              #   language: java
              #   versions:
              #     - openjdk8
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16java
                tag: 0.9.1
        execution:
          onExecute:
            - printenv
            - echo $test
            - echo $ribbit
            - pushd $res_script_repo1_resourcePath
            - source example.env
            - echo ~
            - ./echo.sh
            - echo $test
            - echo $ribbit
            - popd

      - name: mvn_build_scan
        type: XrayScan
        configuration:
          nodePool: TestPoolAkhil
          #waitUntilFinish: false
          inputResources:
            - name: mvnBuild_info
          outputResources:
            - name: mvnBuild_infoScaned
