resources:
  - name: same_gitRepo1
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/pipelines
      branches:
        include: simple

  - name: gitRepo_githubhttps
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple
      cloneProtocol: https
      branches:
        include: main

  - name: gitRepo_gitlabhttps
    type: GitRepo
    configuration:
      gitProvider: s_gitLab
      path: jfbeta/test
      cloneProtocol: https
      branches:
        include: main

  - name: gitRepo_bitbuckethttps
    type: GitRepo
    configuration:
      gitProvider: vijay_bitbucket
      path: jfbeta/webhook
      cloneProtocol: https

  #   - name: gitRepo_bitbucketserverhttps
  #     type: GitRepo
  #     configuration:
  #       gitProvider: vijay_bitbucketserver
  #       path: ~vijaykp/sample-tests
  #       cloneProtocol: https

  - name: gitRepo_github
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple
      branches:
        include: main

  - name: gitRepo_gitlab
    type: GitRepo
    configuration:
      gitProvider: s_gitLab
      path: jfbeta/test
      branches:
        include: main

  - name: gitRepo_bitbucket
    type: GitRepo
    configuration:
      gitProvider: vijay_bitbucket
      path: jfbeta/webhook

  #   - name: gitRepo_bitbucketserver
  #     type: GitRepo
  #     configuration:
  #       gitProvider: vijay_bitbucketserver
  #       path: ~vijaykp/sample-tests

  - name: versionbag
    type: PropertyBag
    configuration:
      version: ''

  - name: branchbag
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag
    type: PropertyBag
    configuration:
      pipeline_v: ''

pipelines:
  - name: simplePipelines1
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          #           timeoutSeconds: 60
          inputResources:
            - name: same_gitRepo1
            - name: gitRepo_githubhttps
            - name: gitRepo_gitlabhttps
            - name: gitRepo_bitbuckethttps
            #             - name: gitRepo_bitbucketserverhttps
            - name: gitRepo_github
            - name: gitRepo_gitlab
            - name: gitRepo_bitbucket
          #             - name: gitRepo_bitbucketserver
          outputResources:
            - name: versionbag
            - name: branchbag
            - name: pipelineVBag
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - write_output versionbag "version=$run_id"
            - write_output branchbag "branch_name=$run_id"
            - write_output pipelineVBag "pipeline_v=$run_id"

      - name: simpleBash2
        type: Bash
        configuration:
          inputResources:
            - name: same_gitRepo1
            - name: gitRepo_githubhttps
        execution:
          onExecute:
            - printenv
      #             - sleep 1m

      - name: simpleBash3
        type: Bash
        configuration:
          inputResources:
            - name: versionbag
            - name: gitRepo_githubhttps
            - name: same_gitRepo1
        execution:
          onExecute:
            - printenv
