resources:
  - name: same_gitRepo_with_big_name_and_bigger_space
    type: GitRepo
    configuration:
      gitProvider: testInt
      path: akhilesh073/TestYmlPipeline
      branches:
        include: withEnvVariables

  - name: gitRepo_githubhttps_With_gitRepo_githubhttps_repo
    type: GitRepo
    configuration:
      gitProvider: testInt
      path: akhilesh073/jfrog-pipelines-matrix-example
      cloneProtocol: https
      branches:
        include: master

  - name: versionbag
    type: PropertyBag
    configuration:
      version: '1.0.0'

  - name: branchbag
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag
    type: PropertyBag
    configuration:
      pipeline_v: ''

pipelines:
  - name: simplePipelines1
    configuration:
      environmentVariables:
        readOnly:
          v1: copper
          v2: carrot
          v3: iron
          v4: broccoli
          v5: copper
          v6: carrot
          v7: iron
          v8: broccoli
          v9: copper
          v10: carrot
          v11: iron
          v12: broccoli
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          environmentVariables:
            s1v1: copper
            s1v2: carrot
            s1v3: iron
            s1v4: broccoli
            s1v5: copper
            s1v6: carrot
            s1v7: iron
            s1v8: broccoli
            s1v9: copper
            s1v10: carrot
            s1v11: iron
            s1v12: broccoli
          #           timeoutSeconds: 60
          inputResources:
            - name: gitRepo_githubhttps_With_gitRepo_githubhttps_repo
          outputResources:
            - name: versionbag
            - name: branchbag
            - name: pipelineVBag
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - echo "aaa bbb ccc"
            - write_output versionbag "version=$run_id"
            - write_output branchbag "branch_name=$run_id"
            - write_output pipelineVBag "pipeline_v=$run_id"
      - name: simpleBash2
        type: Bash
        configuration:
          environmentVariables:
            s1v1: copper
            s1v2: carrot
            s1v3: iron
            s1v4: broccoli
            s1v5: copper
            s1v6: carrot
            s1v7: iron
            s1v8: broccoli
            s1v9: copper
            s1v10: carrot
            s1v11: iron
            s1v12: broccoli
          inputSteps:
            - name: simpleBash1
          inputResources:
            - name: versionbag
        execution:
          onExecute:
            - printenv
      - name: simpleBash_abc
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash1
          inputResources:
            - name: gitRepo_githubhttps_With_gitRepo_githubhttps_repo
        execution:
          onExecute:
            - printenv
      - name: simpleBash311
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash_abc
          inputResources:
            - name: versionbag
            - name: gitRepo_githubhttps_With_gitRepo_githubhttps_repo
          outputResources:
            - name: same_gitRepo_with_big_name_and_bigger_space
        execution:
          onExecute:
            - printenv
            - echo "${res_versionbag_version}"
      - name: simpleBash411
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash311
          inputResources:
            - name: versionbag
          outputResources:
            - name: same_gitRepo_with_big_name_and_bigger_space
        execution:
          onExecute:
            - printenv
            - echo "${res_versionbag_version}"
