resources:
  - name: R0
    type: PropertyBag
    configuration:
      version: '1.0.0'
  - name: R1
    type: PropertyBag
    configuration:
      version: '1.0.0'
  - name: R2
    type: PropertyBag
    configuration:
      version: '1.0.0'
  - name: R3
    type: PropertyBag
    configuration:
      version: '1.0.0'
  - name: R4
    type: PropertyBag
    configuration:
      version: '1.0.0'
pipelines:
  - name: runTriggerWithResource
    steps:
      - name: A
        type: Bash
        configuration:
          inputResources:
            - name: R0
          outputResources:
            - name: R1
        execution:
          onExecute:
            - printenv
            - echo "Step A"
      - name: B
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin
          inputResources:
            - name: R1
          outputResources:
            - name: R2
            - name: R3
          inputSteps:
            - name: A
        execution:
          onExecute:
            - printenv
            - echo "Step B"
      - name: C
        type: Bash
        configuration:
          inputResources:
            - name: R2
          outputResources:
            - name: R4
        execution:
          onExecute:
            - printenv
            - echo "Step C"
      - name: D
        type: Bash
        configuration:
          inputResources:
            - name: R4
        execution:
          onExecute:
            - printenv
            - echo "Step D"
      - name: E
        type: Bash
        configuration:
          inputResources:
            - name: R3
        execution:
          onExecute:
            - printenv
            - echo "Step E"
