pipelines:
  - name: varsha_Matrix_test
    steps:
      - name: S_Matrix_0048pre
        type: PreMatrix
        execution:
          onExecute:
            - echo "Preparing the code base"
            - npm install
            - echo "Installed npm"

      - name: S_Matrix_0048mat
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: S_Matrix_0048pre
        stepletMultipliers:
          environmentVariables:
            - animal: dog
              bird: sparrow
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 12

        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - echo "Variation animal = ${animal}, bird = ${bird}"

      - name: S_Matrix_0048post
        type: PostMatrix
        configuration:
          inputSteps:
            - name: S_Matrix_0048mat
        execution:
          onExecute:
            - echo "Executing the output step"
