pipelines:
  - name: a_pipeline_with_long_long_name_and_still_long_name
    steps:
      - name: singleStepBash1
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin
        execution:
          onExecute:
            - echo "Hiii"
