resources:
  - name: propertyCanvas
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      pipelines: 'user_in'
  - name: propertyCanvas2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines:
  - name: single_test_without_resource
    configuration:
      environmentVariables:
        readOnly:
          pipevar1: 1
          pipevar2: 2
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - aaa
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_1
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - bbb
            - echo "done"
      - name: trigger_3
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_2
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
      - name: trigger_4
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_3
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
      - name: trigger_5
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_4
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
      - name: trigger_6
        type: Bash
        configuration:
          affinityGroup: trigger
          inputSteps:
            - name: trigger_5
          environmentVariables:
            env1: 1
            env2:
              default: 2
              description: someDescription
          priority: 0
        execution:
          onExecute:
            - printenv
            - echo "done"
