pipelines:
  - name: singleStep
    configuration:
      environmentVariables:
        readOnly:
          env1: value1
          env2:
            default: value1
            description: env2 description
            values:
              - value1
              - value2
              - value3
            allowCustom: true
    steps:
      - name: singleStepBash1
        type: Bash
        configuration:
          environmentVariables:
            env3: value3
            env4: value4
        execution:
          onExecute:
            - printenv
