resources:
  - name: versionbag1
    type: PropertyBag
    configuration:
      version: '1.0.0'

  - name: branchbag1
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag2
    type: PropertyBag
    configuration:
      pipeline_v: ''
  - name: pipelineVBag3
    type: PropertyBag
    configuration:
      pipeline_v: ''

pipelines:
  - name: simplePipelines1
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          outputResources:
            - name: versionbag1
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - echo "aaa bbb ccc"
            - write_output versionbag1 "version=$run_id"
      - name: simpleBash_abc
        type: Bash
        configuration:
          inputResources:
            - name: pipelineVBag2
          outputResources:
            - name: branchbag1
        execution:
          onExecute:
            - printenv
            - write_output branchbag1 "branch_name=$run_id"
      - name: simpleBash2
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash1
            - name: simpleBash_abc
          inputResources:
            - name: versionbag1
            - name: pipelineVBag2
        execution:
          onExecute:
            - printenv
      - name: simpleBash4
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash2
          inputResources:
            - name: branchbag1
        execution:
          onExecute:
            - printenv
            - echo "${res_versionbag_version}"
