pipelines:
  - name: jfdev_repo_creation_sample
    configuration:
      chronological: true
    steps:
      - name: create_repos
        type: Bash
        configuration:
          environmentVariables:
            BRANCH_NAME: 'BRANCH_NAME'
            Pipeline_name: 'Pipeline_name'
            Field_1: 'Field_1'
            Field_2: 'Field_2'
            Field_3: 'Field_3'
            Field_4: 'Field_4'
            Field_5: 'Field_5'
            Field_6: 'Field_6'
            Field_7: 'Field_7'
            Field_8: 'Field_8'
            Field_9: 'Field_9'
        execution:
          onStart:
            - >-
              if [ -z "$BRANCH_NAME" ]; then echo "pass in a branch name"; exit 1;
              fi
            - >-
              export BRANCH_LOWERCASE_NAME=$(echo ${BRANCH_NAME} | tr A-Z a-z | tr
              "/" "-")
            - echo $BRANCH_LOWERCASE_NAME
          onExecute:
            - printenv
