pipelines:
  - name: singleStep
    steps:
      - name: singleStepBash1
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin
        execution:
          onExecute:
            - echo "Hiii"
