resources:
  - name: self_repo
    type: GitRepo
    configuration:
      gitProvider: testInt
      path: akhilesh073/TestYmlPipeline
      branches:
        include: ^tests$

pipelines:
  - name: 1234-very-long-name-very-long-name-very-long-name-very-long-name-very-long-name-very-long-name-very-long-name-very-long
    steps:
      - name: Normal_Step
        type: Bash
        configuration:
          inputResources:
            - name: self_repo
        execution:
          onExecute:
            - pushd "$res_self_repo_resourcePath/"
            - save_tests saveTests/failing
            - echo "Passed s"
            - popd
