resources:
  - name: versionbag113
    type: PropertyBag
    configuration:
      version: '1.0.0'

  - name: branchbag113
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag113
    type: PropertyBag
    configuration:
      pipeline_v: ''
  - name: environmentSetupBag
    type: PropertyBag
    configuration:
      pipelinesVersion: ''
      serverName: ''
      masterKey: ''

pipelines:
  - name: simplePipelines2
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          outputResources:
            - name: versionbag113
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - echo "aaa bbb ccc"
            - write_output versionbag113 "version=$run_id"
      - name: simpleBash_abc
        type: DockerBuild
        configuration:
          inputResources:
            - name: pipelineVBag113
          outputResources:
            - name: branchbag113
        execution:
          onExecute:
            - printenv1113
            - write_output branchbag113 "branch_name=$run_id"
      - name: branch_environment_setup
          type: Jenkins
          configuration:
            inputResources:
              - name: environmentSetupBag
            jenkinsJobName: tools/platform/environment_setup
      - name: simpleBash2
        type: Jenkins
        configuration:
          inputSteps:
            - name: simpleBash1
            - name: simpleBash_abc
          inputResources:
            - name: versionbag113
            - name: pipelineVBag113
        execution:
          onExecute:
            - printenv
      - name: simpleBash4
        type: MvnBuild
        configuration:
          inputSteps:
            - name: simpleBash2
          inputResources:
            - name: branchbag113
        execution:
          onExecute:
            - printenv
