resources:
  # - name: same_gitRepo1
  #   type: GitRepo
  #   configuration:
  #     gitProvider: testInt
  #     path: akhilesh073/TestYmlPipeline
  #     branches:
  #       include: master

  # - name: gitRepo_githubhttps
  #   type: GitRepo
  #   configuration:
  #     gitProvider: testInt
  #     path: akhilesh073/LocalTemplatePipeline
  #     cloneProtocol: https
  #     branches:
  #       include: main

  - name: versionbag
    type: PropertyBag
    configuration:
      version: '1.0.0'

  - name: branchbag
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag
    type: PropertyBag
    configuration:
      pipeline_v: ''

pipelines:
  - name: simplePipelines1
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          #           timeoutSeconds: 60
          inputResources:
            - name: branchbag
          outputResources:
            - name: versionbag
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - echo "aaa bbb ccc"
            - write_output versionbag "version=$run_id"
      - name: simpleBash_abc
        type: Bash
        configuration:
          inputResources:
            - name: branchbag
          outputResources:
            - name: branchbag
        execution:
          onExecute:
            - printenv
            - write_output branchbag "branch_name=$run_id"
      - name: simpleBash2
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash1
            - name: simpleBash_abc
          inputResources:
            - name: versionbag
            - name: branchbag
        execution:
          onExecute:
            - printenv
      - name: simpleBash4
        type: Bash
        configuration:
          inputSteps:
            - name: simpleBash2
          inputResources:
            - name: branchbag
        execution:
          onExecute:
            - printenv
            - echo "${res_versionbag_version}"
