resources:
  - name: versionbag111
    type: PropertyBag
    configuration:
      version: '1.0.0'

  - name: branchbag111
    type: PropertyBag
    configuration:
      branch_name: ''

  - name: pipelineVBag111
    type: PropertyBag
    configuration:
      pipeline_v: ''

pipelines:
  - name: simplePipelines2
    steps:
      - name: simpleBash1
        type: Bash
        configuration:
          outputResources:
            - name: versionbag111
        execution:
          onExecute:
            - printenv
            #             - sleep 3m
            - echo "aaa bbb ccc"
            - write_output versionbag111 "version=$run_id"
      - name: simpleBash_abc
        type: DockerBuild
        configuration:
          dockerImageName: 'testDocker'
          dockerImageTag: 'testTag'
          inputResources:
            - name: pipelineVBag111
          outputResources:
            - name: branchbag111
      - name: simpleBash2
        type: Jenkins
        configuration:
          jenkinsJobName: 'testJenkin'
          inputSteps:
            - name: simpleBash1
            - name: simpleBash_abc
          inputResources:
            - name: versionbag111
            - name: pipelineVBag111
        execution:
          onExecute:
            - printenv
      - name: simpleBash4
        type: MvnBuild
        configuration:
          inputSteps:
            - name: simpleBash2
          inputResources:
            - name: branchbag111
        execution:
