pipelines:
  - name: runTriggerWithoutResource
    steps:
      - name: A
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "Step A"
      - name: B
        type: Bash
        configuration:
          inputSteps:
            - name: A
        execution:
          onExecute:
            - printenv
            - echo "Step B"
      - name: C
        type: Bash
        configuration:
          inputSteps:
            - name: B
        execution:
          onExecute:
            - printenv
            - echo "Step C"
      - name: D
        type: Bash
        configuration:
          inputSteps:
            - name: C
        execution:
          onExecute:
            - printenv
            - echo "Step D"
      - name: E
        type: Bash
        configuration:
          inputSteps:
            - name: B
        execution:
          onExecute:
            - printenv
            - echo "Step E"
